import re
from pathlib import Path

import anthropic

from . import __version__
from .models import CUSTOM_MARKER, GENERATED_MARKER, GeneratedFile, ProjectContext, Standard


def generate_test(standard: Standard, ctx: ProjectContext) -> str:
    client = anthropic.Anthropic()

    prompt = _build_prompt(standard, ctx)

    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=4096,
        messages=[{"role": "user", "content": prompt}],
    )

    raw = message.content[0].text
    return _extract_code(raw)


def generate_claude_md_update(
    standards: list[Standard], ctx: ProjectContext, existing_claude_md: str
) -> str:
    client = anthropic.Anthropic()

    sections = "\n\n".join(s.claude_md_section for s in standards)
    existing = existing_claude_md or "(no existing CLAUDE.md)"

    prompt = f"""You are updating a CLAUDE.md file for a software project. CLAUDE.md files contain
instructions for AI assistants (Claude Code) working in the project.

Project context:
{ctx.summary()}

The following standards have been applied to this project. Each standard has a CLAUDE.md section
that should be included so that Claude understands the conventions when writing or reviewing code.

Standards sections to incorporate:
{sections}

Existing CLAUDE.md content:
{existing}

Instructions:
- Merge the standards sections into the CLAUDE.md without duplicating content that already exists
- Keep any existing project-specific content
- Use clear markdown headings
- Be concise — these are instructions, not documentation
- Output ONLY the full updated CLAUDE.md content, no explanation
"""

    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=4096,
        messages=[{"role": "user", "content": prompt}],
    )

    return message.content[0].text.strip()


def wrap_with_header(content: str, standard_id: str) -> str:
    header = (
        f"{GENERATED_MARKER} v{__version__} | standard: {standard_id}\n"
        f"# Re-generate: agency-standards update {standard_id}\n"
        f"{CUSTOM_MARKER}\n\n"
    )
    return header + content


def preserve_custom_section(old_content: str, new_content: str) -> str:
    """Keep anything after CUSTOM_MARKER from the old file, append to new generated content."""
    if CUSTOM_MARKER in old_content:
        _, custom = old_content.split(CUSTOM_MARKER, 1)
        custom = custom.strip()
    else:
        custom = ""

    # Strip header from new content if present
    if CUSTOM_MARKER in new_content:
        header_and_body, _ = new_content.split(CUSTOM_MARKER, 1)
        base = header_and_body + CUSTOM_MARKER + "\n"
    else:
        base = new_content + "\n" + CUSTOM_MARKER + "\n"

    if custom:
        return base + "\n" + custom + "\n"
    return base


def get_standard_version(content: str) -> str | None:
    match = re.search(r"GENERATED by agency-standards v([\d.]+)", content)
    return match.group(1) if match else None


def get_standard_id(content: str) -> str | None:
    match = re.search(r"standard: ([\w-]+)", content)
    return match.group(1) if match else None


def _build_prompt(standard: Standard, ctx: ProjectContext) -> str:
    sample_tests = ctx.sample_test_source()
    sample_src = ctx.sample_src_source()

    test_dirs_str = ", ".join(str(p.relative_to(ctx.root)) for p in ctx.test_dirs)
    src_dirs_str = ", ".join(str(p.relative_to(ctx.root)) for p in ctx.src_dirs)

    return f"""{standard.prompt}

Project context:
{ctx.summary()}

Test directories: {test_dirs_str}
Source directories: {src_dirs_str}

Sample existing test files (for context on style and naming):
{sample_tests or "(no existing test files found)"}

Sample source files (for context on module structure):
{sample_src or "(no source files found)"}

Requirements:
- Output ONLY valid Python code, no markdown fences, no explanation
- The file must work with pytest discovery (test functions or test classes)
- Use Python's ast module for static analysis where appropriate
- Be specific to this project's actual directory structure and file patterns
- Add a descriptive docstring explaining what the test enforces
- Each test method should have a clear failure message
"""


def _extract_code(text: str) -> str:
    """Strip markdown code fences if the model wrapped the output."""
    text = text.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        # remove first and last fence lines
        start = 1
        end = len(lines)
        for i in range(len(lines) - 1, 0, -1):
            if lines[i].strip() == "```":
                end = i
                break
        return "\n".join(lines[start:end]).strip()
    return text
