from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class Standard:
    id: str
    name: str
    description: str
    languages: list[str]
    output_file: str
    prompt: str
    claude_md_section: str
    source: str = "builtin"  # builtin | local | custom
    tags: list[str] = field(default_factory=list)  # general | bdd | e2e


@dataclass
class ProjectContext:
    root: Path
    src_dirs: list[Path] = field(default_factory=list)
    test_dirs: list[Path] = field(default_factory=list)
    unit_test_files: list[Path] = field(default_factory=list)
    integration_test_files: list[Path] = field(default_factory=list)
    src_files: list[Path] = field(default_factory=list)
    languages: list[str] = field(default_factory=list)
    project_type: str = "unknown"  # api | cli | library | unknown
    pyproject: dict = field(default_factory=dict)
    existing_arch_tests: list[Path] = field(default_factory=list)
    uses_bdd: bool = False
    feature_files: list[Path] = field(default_factory=list)
    step_dirs: list[Path] = field(default_factory=list)  # given/ when/ then/ dirs

    def summary(self) -> str:
        lines = [
            f"Root: {self.root}",
            f"Languages: {', '.join(self.languages) or 'unknown'}",
            f"Project type: {self.project_type}",
            f"Source dirs: {[str(p.relative_to(self.root)) for p in self.src_dirs]}",
            f"Test dirs: {[str(p.relative_to(self.root)) for p in self.test_dirs]}",
            f"Unit test files ({len(self.unit_test_files)}): "
            + ", ".join(p.name for p in self.unit_test_files[:5])
            + ("..." if len(self.unit_test_files) > 5 else ""),
            f"Integration test files ({len(self.integration_test_files)}): "
            + ", ".join(p.name for p in self.integration_test_files[:5])
            + ("..." if len(self.integration_test_files) > 5 else ""),
            f"Existing arch tests: {[p.name for p in self.existing_arch_tests]}",
        ]
        lines.append(f"Uses BDD: {self.uses_bdd}")
        if self.feature_files:
            lines.append(f"Feature files ({len(self.feature_files)}): "
                + ", ".join(p.name for p in self.feature_files[:5]))
        if self.step_dirs:
            lines.append(f"Step dirs: {[str(p.relative_to(self.root)) for p in self.step_dirs[:6]]}")
        if self.pyproject:
            deps = self.pyproject.get("project", {}).get("dependencies", [])
            lines.append(f"Dependencies: {deps[:10]}")
        return "\n".join(lines)

    def sample_test_source(self, max_files: int = 3, max_lines: int = 50) -> str:
        samples = []
        files = (self.unit_test_files + self.integration_test_files)[:max_files]
        for f in files:
            try:
                lines = f.read_text().splitlines()[:max_lines]
                rel = f.relative_to(self.root)
                samples.append(f"# --- {rel} ---\n" + "\n".join(lines))
            except Exception:
                pass
        return "\n\n".join(samples)

    def sample_src_source(self, max_files: int = 3, max_lines: int = 50) -> str:
        samples = []
        for f in self.src_files[:max_files]:
            try:
                lines = f.read_text().splitlines()[:max_lines]
                rel = f.relative_to(self.root)
                samples.append(f"# --- {rel} ---\n" + "\n".join(lines))
            except Exception:
                pass
        return "\n\n".join(samples)


@dataclass
class GeneratedFile:
    standard_id: str
    path: Path
    content: str
    version: str


GENERATED_MARKER = "# GENERATED by agency-standards"
CUSTOM_MARKER = "# --- CUSTOM (preserved on update) ---"
