from pathlib import Path

import questionary
from rich.console import Console

from ..generator import generate_test, get_standard_id, get_standard_version, preserve_custom_section, wrap_with_header
from ..inspector import inspect
from ..standards.loader import load_by_id

console = Console()


def run(target: Path, standard_id: str | None = None) -> None:
    ctx = inspect(target)
    arch_dirs = [d / "architecture" for d in ctx.test_dirs if (d / "architecture").exists()]

    if not arch_dirs:
        console.print("[yellow]No tests/architecture/ directory found. Run init first.[/yellow]")
        return

    arch_dir = arch_dirs[0]
    # Glob all files in the arch dir, filter to generated ones (language-agnostic)
    generated_files = [f for f in arch_dir.iterdir() if f.is_file() and _is_generated(f)]

    if standard_id:
        generated_files = [f for f in generated_files if get_standard_id(f.read_text()) == standard_id]

    if not generated_files:
        console.print("[yellow]No generated files found to update.[/yellow]")
        return

    console.print(f"Found {len(generated_files)} generated file(s) to update:")
    for f in generated_files:
        sid = get_standard_id(f.read_text())
        ver = get_standard_version(f.read_text())
        console.print(f"  [cyan]{f.name}[/cyan] (standard: {sid}, generated at v{ver})")

    if not questionary.confirm("Regenerate these files?", default=True).ask():
        return

    for path in generated_files:
        old_content = path.read_text()
        sid = get_standard_id(old_content)
        if not sid:
            continue

        standard = load_by_id(sid)
        if not standard:
            console.print(f"  [yellow]Standard '{sid}' not found, skipping {path.name}[/yellow]")
            continue

        console.print(f"  Updating [cyan]{path.name}[/cyan]...", end=" ")
        try:
            new_code = generate_test(standard, ctx)
            new_content = wrap_with_header(new_code, sid)
            final = preserve_custom_section(old_content, new_content)
            path.write_text(final)
            console.print("[green]done[/green]")
        except Exception as e:
            console.print(f"[red]failed: {e}[/red]")


def _is_generated(path: Path) -> bool:
    try:
        return "GENERATED by agency-standards" in path.read_text()
    except Exception:
        return False
